version: '3'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: example_password
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./mariadb-config:/etc/mysql/mariadb.conf.d
    ports:
      - 3307:3306
